### PR TITLE
Add gcs-downloader Dockerfile & main binary

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change adds the main logic for the gcs-downloader.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/gcs-downloader/2)

### CODE REVIEW

**Review by pboothe — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/gcs-downloader/2)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe and @stephen-soltesz)

___
*[main.go, line 39 at r1](https://reviewable.io/reviews/m-lab/gcs-downloader/2#-LcIL2_KDLqFsHC0jwXA:-LcIL2_KDLqFsHC0jwXB:b7x4eiq) ([raw file](https://github.com/m-lab/gcs-downloader/blob/f61419b3e6875dcd39ab565a8c213509c7b3d7c2/main.go#L39)):*
> ```Go
> }
> 
> var tempNew = atomicfile.New
> ```

call this `atomicfileNew`
___
*[main.go, line 48 at r1](https://reviewable.io/reviews/m-lab/gcs-downloader/2#-LcIKswUEQiUVQ_e5u2M:-LcIKswUEQiUVQ_e5u2N:b-7ei593) ([raw file](https://github.com/m-lab/gcs-downloader/blob/f61419b3e6875dcd39ab565a8c213509c7b3d7c2/main.go#L48)):*
> ```Go
> 			err := atomicfile.SaveFile(ctx, o, tempNew(path.Join(output, o.LocalName())))
> 			if err != nil {
> 				log.Println(err)
> ```

Missing `return err` ?
___
*[main_test.go, line 24 at r1](https://reviewable.io/reviews/m-lab/gcs-downloader/2#-LcILTS-BGs-lERit_S8:-LcILTS-BGs-lERit_S9:b-do2i3l) ([raw file](https://github.com/m-lab/gcs-downloader/blob/f61419b3e6875dcd39ab565a8c213509c7b3d7c2/main_test.go#L24)):*
> ```Go
> 		tempFile atomicfile.File
> 	}{
> 		{
> ```

If /tmp/junk exists, does this test fail?  Can we use ioutil.Tempdir instead to ensure we know what is in there?
___
*[main_test.go, line 46 at r1](https://reviewable.io/reviews/m-lab/gcs-downloader/2#-LcILEWSENqBNA9qlw1j:-LcILEWSENqBNA9qlw1k:b-u2id0f) ([raw file](https://github.com/m-lab/gcs-downloader/blob/f61419b3e6875dcd39ab565a8c213509c7b3d7c2/main_test.go#L46)):*
> ```Go
> }
> 
> type fakeTemp struct {
> ```

fakeAtomicfile

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/gcs-downloader/2)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe)

___
*[main.go, line 39 at r1](https://reviewable.io/reviews/m-lab/gcs-downloader/2#-LcIL2_KDLqFsHC0jwXA:-LcINH_O9rQNV3khAeVC:b-896fix) ([raw file](https://github.com/m-lab/gcs-downloader/blob/f61419b3e6875dcd39ab565a8c213509c7b3d7c2/main.go#L39)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

call this `atomicfileNew`
</blockquote></details>

Done.
___
*[main.go, line 48 at r1](https://reviewable.io/reviews/m-lab/gcs-downloader/2#-LcIKswUEQiUVQ_e5u2M:-LcIOwhWE89budJDBO4h:b-xyz578) ([raw file](https://github.com/m-lab/gcs-downloader/blob/f61419b3e6875dcd39ab565a8c213509c7b3d7c2/main.go#L48)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Missing `return err` ?
</blockquote></details>

My thinking had been to keep trying since bucket.Walk stops walking if `visit` returns an error. But that may not be as helpful as I originally thought. So, I'll just return on error and try again on the next `memoryless.Run`. And, I also noticed that I wasn't handling the error return by `bucket.Walk` -- so, I'm doing that now too.
___
*[main_test.go, line 24 at r1](https://reviewable.io/reviews/m-lab/gcs-downloader/2#-LcILTS-BGs-lERit_S8:-LcINXPG6tWxPNplFI0r:b-896fix) ([raw file](https://github.com/m-lab/gcs-downloader/blob/f61419b3e6875dcd39ab565a8c213509c7b3d7c2/main_test.go#L24)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

If /tmp/junk exists, does this test fail?  Can we use ioutil.Tempdir instead to ensure we know what is in there?
</blockquote></details>

Done.
___
*[main_test.go, line 46 at r1](https://reviewable.io/reviews/m-lab/gcs-downloader/2#-LcILEWSENqBNA9qlw1j:-LcINXBdDRnP_4F-RgEH:b-896fix) ([raw file](https://github.com/m-lab/gcs-downloader/blob/f61419b3e6875dcd39ab565a8c213509c7b3d7c2/main_test.go#L46)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

fakeAtomicfile
</blockquote></details>

Done.

**Review by pboothe — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/gcs-downloader/2)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pboothe and @stephen-soltesz)

___
*[main_test.go, line 24 at r1](https://reviewable.io/reviews/m-lab/gcs-downloader/2#-LcILTS-BGs-lERit_S8:-LcIW8hOA9R2OeLB_1Lr:b-ytud2b) ([raw file](https://github.com/m-lab/gcs-downloader/blob/f61419b3e6875dcd39ab565a8c213509c7b3d7c2/main_test.go#L24)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Add `defer ioutil.RemoveAll(dir)`

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/gcs-downloader/2)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pboothe)

___
*[main_test.go, line 24 at r1](https://reviewable.io/reviews/m-lab/gcs-downloader/2#-LcILTS-BGs-lERit_S8:-LcIY2aXBSQWYPVxmN91:b-896fix) ([raw file](https://github.com/m-lab/gcs-downloader/blob/f61419b3e6875dcd39ab565a8c213509c7b3d7c2/main_test.go#L24)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Add `defer ioutil.RemoveAll(dir)`
</blockquote></details>

Done.

**Pull request merged**
